### ISSUE TITLE
Slow initialization

### ISSUE THREAD

**Issue by sklose** [NKnusperer/BetterConfigurationManager#1]
I just tried this plugin with a solution that has 177 projects and each project has ~20 build configurations. After everything is loaded the speed of the UI is great: very snappy, no delays and I can finally assign a configuration to every single project with one click instead of doing it one by one. The only issue is the initial load time. It took around 5 minutes of Visual Studio being unresponsive and one CPU core being maxed out until the configuration manager came up. Is there any way to optimize the load procedure?

**Comment by NKnusperer** [comment]
Hello sklose,
I will try to investigate into this issue over the weekend and will give feedback here.

**Comment by NKnusperer** [comment]
Just an quick update, I had no time to work on this issues yet but will now start and hopefully fix it till end of the week.

**Comment by NKnusperer** [comment]
Hi sklose,
v1.1 was just released which no longer blocks Visual Studio while loading.
I could not really speedup the loading progress itself because it looks like that Visual Studio is doing some kind of locking while accessing internal data so any try to parallelize the loading resulted in a massive loading slowdown.

**Comment by sklose** [comment]
Thanks for the fix, Visual Studio doesn't lock up anymore
