### ISSUE TITLE
Cannot install on VS2019

### ISSUE THREAD

**Issue by LukeOrdelmans** [NKnusperer/BetterConfigurationManager#4]
installer fails on VS2019, see log file
[dd_VSIXInstaller_20190731105114_2128.log](https://github.com/NKnusperer/BetterConfigurationManager/files/3450696/dd_VSIXInstaller_20190731105114_2128.log)

**Comment by Tdue21** [comment]
Still a problem it appears: 
![image](https://user-images.githubusercontent.com/2953375/109624635-b896a000-7b3e-11eb-9321-4fc1ddd85323.png)

**Comment by NKnusperer** [comment]
Unfortunately this project is no longer maintained simply because I stopped using Visual Studio and switched to JetBrains Rider.
Anyhow, VS2019 support was implemented in #5 but I haven't tested it.
I will setup a VS2019 instance today and if everything is working publish a new package.
Thank you for your patience.

**Comment by NKnusperer** [comment]
I just published v1.3 with VS2019 support.

**Comment by Tdue21** [comment]
It works beautifully, thanks :)
